---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: deps
    labels:
      - dependencies
    cooldown:
      default-days: 7
      exclude:
        - "euroscope-rust/actions/*"
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: deps
    labels:
      - dependencies
    cooldown:
      default-days: 7
  - package-ecosystem: rust-toolchain
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: deps
    labels:
      - dependencies
    cooldown:
      default-days: 7