//! Built-in tag item / function codes from the EuroScope SDK.
//!
//! These are large sets of integer input codes (used with
//! `CFlightPlanList` columns and `start_tag_function`), so they are exposed as
//! `pub const i32` rather than enums.

/// Built-in tag item codes (columns) for flight-plan lists and displays.
///
/// Mirrors the SDK's `TAG_ITEM_TYPE_*` constants.
pub mod tag_item_type {
    /// `TAG_ITEM_TYPE_NEXT_LINE`
    pub const NEXT_LINE: i32 = 0;
    /// `TAG_ITEM_TYPE_STATIC_STRING`
    pub const STATIC_STRING: i32 = 1;
    /// `TAG_ITEM_TYPE_SQUAWK`
    pub const SQUAWK: i32 = 2;
    /// `TAG_ITEM_TYPE_VERTICAL_SPEED_INDICATOR`
    pub const VERTICAL_SPEED_INDICATOR: i32 = 3;
    /// `TAG_ITEM_TYPE_ALTITUDE`
    pub const ALTITUDE: i32 = 4;
    /// `TAG_ITEM_TYPE_EMERGENCY_INDICATOR`
    pub const EMERGENCY_INDICATOR: i32 = 5;
    /// `TAG_ITEM_TYPE_RADIO_FAILURE_INDICATOR`
    pub const RADIO_FAILURE_INDICATOR: i32 = 6;
    /// `TAG_ITEM_TYPE_HIJACK_INDICATOR`
    pub const HIJACK_INDICATOR: i32 = 7;
    /// `TAG_ITEM_TYPE_COLLOSION_ALERT`
    pub const COLLOSION_ALERT: i32 = 8;
    /// `TAG_ITEM_TYPE_CALLSIGN`
    pub const CALLSIGN: i32 = 9;
    /// `TAG_ITEM_TYPE_AIRCRAFT_CATEGORY`
    pub const AIRCRAFT_CATEGORY: i32 = 10;
    /// `TAG_ITEM_TYPE_COMMUNICATION_TYPE`
    pub const COMMUNICATION_TYPE: i32 = 11;
    /// `TAG_ITEM_TYPE_VERTICAL_SPEED`
    pub const VERTICAL_SPEED: i32 = 12;
    /// `TAG_ITEM_TYPE_GROUND_SPEED_WITH_N`
    pub const GROUND_SPEED_WITH_N: i32 = 13;
    /// `TAG_ITEM_TYPE_HANDOFF_TARGET`
    pub const HANDOFF_TARGET: i32 = 14;
    /// `TAG_ITEM_TYPE_OWNER`
    pub const OWNER: i32 = 15;
    /// `TAG_ITEM_TYPE_PLANE_TYPE`
    pub const PLANE_TYPE: i32 = 16;
    /// `TAG_ITEM_TYPE_DESTINATION`
    pub const DESTINATION: i32 = 17;
    /// `TAG_ITEM_TYPE_SQUAWK_ERROR`
    pub const SQUAWK_ERROR: i32 = 18;
    /// `TAG_ITEM_TYPE_INFO_STRING`
    pub const INFO_STRING: i32 = 19;
    /// `TAG_ITEM_TYPE_TEMP_ALTITUDE`
    pub const TEMP_ALTITUDE: i32 = 20;
    /// `TAG_ITEM_TYPE_INFO_INDICATOR`
    pub const INFO_INDICATOR: i32 = 21;
    /// `TAG_ITEM_TYPE_FINAL_ALTITUDE`
    pub const FINAL_ALTITUDE: i32 = 22;
    /// `TAG_ITEM_TYPE_ASSIGNED_SPEED`
    pub const ASSIGNED_SPEED: i32 = 23;
    /// `TAG_ITEM_TYPE_ASSIGNED_RATE`
    pub const ASSIGNED_RATE: i32 = 24;
    /// `TAG_ITEM_TYPE_ASSIGNED_HEADING`
    pub const ASSIGNED_HEADING: i32 = 25;
    /// `TAG_ITEM_TYPE_SECTOR_INDICATOR`
    pub const SECTOR_INDICATOR: i32 = 26;
    /// `TAG_ITEM_TYPE_DUPLICATED_SQUAWK`
    pub const DUPLICATED_SQUAWK: i32 = 27;
    /// `TAG_ITEM_TYPE_COPN_COPX_NAME`
    pub const COPN_COPX_NAME: i32 = 28;
    /// `TAG_ITEM_TYPE_COPN_COPX_ALTITUDE`
    pub const COPN_COPX_ALTITUDE: i32 = 29;
    /// `TAG_ITEM_TYPE_FIR_COPX_NAME`
    pub const FIR_COPX_NAME: i32 = 30;
    /// `TAG_ITEM_TYPE_COPX_NOT_CLEARED_ALTITUDE`
    pub const COPX_NOT_CLEARED_ALTITUDE: i32 = 31;
    /// `TAG_ITEM_TYPE_COPX_AWERE_TEMP_ALTITUDE`
    pub const COPX_AWERE_TEMP_ALTITUDE: i32 = 32;
    /// `TAG_ITEM_TYPE_NEXT_LINE_IF_NOT_EMPTY`
    pub const NEXT_LINE_IF_NOT_EMPTY: i32 = 33;
    /// `TAG_ITEM_TYPE_DIRECT`
    pub const DIRECT: i32 = 34;
    /// `TAG_ITEM_TYPE_GROUND_SPEED_OPTIONAL_WITH_N`
    pub const GROUND_SPEED_OPTIONAL_WITH_N: i32 = 35;
    /// `TAG_ITEM_TYPE_FIR_COPX_NAME_OPTIONAL`
    pub const FIR_COPX_NAME_OPTIONAL: i32 = 36;
    /// `TAG_ITEM_TYPE_DESTINATION_OPTIONAL`
    pub const DESTINATION_OPTIONAL: i32 = 37;
    /// `TAG_ITEM_TYPE_PLANE_TYPE_OPTIONAL`
    pub const PLANE_TYPE_OPTIONAL: i32 = 38;
    /// `TAG_ITEM_TYPE_TSSR`
    pub const TSSR: i32 = 39;
    /// `TAG_ITEM_TYPE_GROUND_SPEED_WOUT_N`
    pub const GROUND_SPEED_WOUT_N: i32 = 40;
    /// `TAG_ITEM_TYPE_GROUND_SPEED_OPTIONAL_WOUT_N`
    pub const GROUND_SPEED_OPTIONAL_WOUT_N: i32 = 41;
    /// `TAG_ITEM_TYPE_COMPOUND_WARNING`
    pub const COMPOUND_WARNING: i32 = 42;
    /// `TAG_ITEM_TYPE_TEMP_IFSET`
    pub const TEMP_IFSET: i32 = 43;
    /// `TAG_ITEM_TYPE_ASSIGNED_SPEED_IFSET`
    pub const ASSIGNED_SPEED_IFSET: i32 = 44;
    /// `TAG_ITEM_TYPE_ASSIGNED_RATE_IFSET`
    pub const ASSIGNED_RATE_IFSET: i32 = 45;
    /// `TAG_ITEM_TYPE_ASSIGNED_HEADING_IFSET`
    pub const ASSIGNED_HEADING_IFSET: i32 = 46;
    /// `TAG_ITEM_TYPE_ASSIGNED_RUNWAY`
    pub const ASSIGNED_RUNWAY: i32 = 47;
    /// `TAG_ITEM_TYPE_COPN_NAME`
    pub const COPN_NAME: i32 = 48;
    /// `TAG_ITEM_TYPE_COPN_ALTITUDE`
    pub const COPN_ALTITUDE: i32 = 49;
    /// `TAG_ITEM_TYPE_COPN_TIME`
    pub const COPN_TIME: i32 = 50;
    /// `TAG_ITEM_TYPE_COPX_NAME`
    pub const COPX_NAME: i32 = 51;
    /// `TAG_ITEM_TYPE_COPX_ALTITUDE`
    pub const COPX_ALTITUDE: i32 = 52;
    /// `TAG_ITEM_TYPE_COPX_TIME`
    pub const COPX_TIME: i32 = 53;
    /// `TAG_ITEM_TYPE_ETA`
    pub const ETA: i32 = 54;
    /// `TAG_ITEM_TYPE_ASSIGNED_STAR`
    pub const ASSIGNED_STAR: i32 = 55;
    /// `TAG_ITEM_TYPE_ASSIGNED_SID`
    pub const ASSIGNED_SID: i32 = 56;
    /// `TAG_ITEM_TYPE_DEPARTURE_ORDER`
    pub const DEPARTURE_ORDER: i32 = 57;
    /// `TAG_ITEM_TYPE_CLEARENCE`
    pub const CLEARENCE: i32 = 58;
    /// `TAG_ITEM_TYPE_GROUND_STATUS`
    pub const GROUND_STATUS: i32 = 59;
    /// `TAG_ITEM_TYPE_ASSIGNED_SQUAWK`
    pub const ASSIGNED_SQUAWK: i32 = 60;
    /// `TAG_ITEM_TYPE_ORIGIN`
    pub const ORIGIN: i32 = 61;
    /// `TAG_ITEM_TYPE_RVSM_FLAG`
    pub const RVSM_FLAG: i32 = 62;
    /// `TAG_ITEM_TYPE_FLIGHT_RULE`
    pub const FLIGHT_RULE: i32 = 63;
    /// `TAG_ITEM_TYPE_SECTOR_INDICATOR_FIX`
    pub const SECTOR_INDICATOR_FIX: i32 = 64;
    /// `TAG_ITEM_TYPE_MANUAL_COORDINATION`
    pub const MANUAL_COORDINATION: i32 = 65;
    /// `TAG_ITEM_TYPE_INFO_ALWAYS`
    pub const INFO_ALWAYS: i32 = 66;
    /// `TAG_ITEM_TYPE_CLAM_WARNING`
    pub const CLAM_WARNING: i32 = 67;
    /// `TAG_ITEM_TYPE_RAM_WARNING`
    pub const RAM_WARNING: i32 = 68;
    /// `TAG_ITEM_TYPE_SQ_OR_CALLSIGN`
    pub const SQ_OR_CALLSIGN: i32 = 69;
    /// `TAG_ITEM_TYPE_TWO_LETTER_GS`
    pub const TWO_LETTER_GS: i32 = 70;
    /// `TAG_ITEM_TYPE_TWO_LETTER_GS_OPTIONAL`
    pub const TWO_LETTER_GS_OPTIONAL: i32 = 71;
    /// `TAG_ITEM_TYPE_TWO_LETTER_ASSIGNED_SPEED`
    pub const TWO_LETTER_ASSIGNED_SPEED: i32 = 72;
    /// `TAG_ITEM_TYPE_TWO_LETTER_ASSIGNED_SPEED_IFSET`
    pub const TWO_LETTER_ASSIGNED_SPEED_IFSET: i32 = 73;
    /// `TAG_ITEM_TYPE_NOT_REACHED_TEMPORARY`
    pub const NOT_REACHED_TEMPORARY: i32 = 74;
    /// `TAG_ITEM_TYPE_NOT_CLEARED_COPN_COPX_ALT`
    pub const NOT_CLEARED_COPN_COPX_ALT: i32 = 75;
    /// `TAG_ITEM_TYPE_AIRCRAFT_CATEGORY_WITH_SLASH`
    pub const AIRCRAFT_CATEGORY_WITH_SLASH: i32 = 76;
    /// `TAG_ITEM_TYPE_NON_RVSM_FLAG`
    pub const NON_RVSM_FLAG: i32 = 77;
    /// `TAG_ITEM_TYPE_AC_TYPE_CATEGORY`
    pub const AC_TYPE_CATEGORY: i32 = 78;
    /// `TAG_ITEM_TYPE_AC_TYPE_CATEGORY_OPTIONAL`
    pub const AC_TYPE_CATEGORY_OPTIONAL: i32 = 79;
    /// `TAG_ITEM_TYPE_COMMUNICATION_TYPE_REDUCED`
    pub const COMMUNICATION_TYPE_REDUCED: i32 = 80;
    /// `TAG_ITEM_TYPE_AIRLINE`
    pub const AIRLINE: i32 = 81;
    /// `TAG_ITEM_TYPE_FP_STATUS`
    pub const FP_STATUS: i32 = 82;
    /// `TAG_ITEM_TYPE_ESTIMATE`
    pub const ESTIMATE: i32 = 83;
    /// `TAG_ITEM_TYPE_ESTIMATE_ALWAYS`
    pub const ESTIMATE_ALWAYS: i32 = 84;
    /// `TAG_ITEM_TYPE_CONFLICTING_AC_CALLSING`
    pub const CONFLICTING_AC_CALLSING: i32 = 85;
    /// `TAG_ITEM_TYPE_CONFLICT_START`
    pub const CONFLICT_START: i32 = 86;
    /// `TAG_ITEM_TYPE_CONFLICT_END`
    pub const CONFLICT_END: i32 = 87;
    /// `TAG_ITEM_TYPE_CONFLICT_TYPE`
    pub const CONFLICT_TYPE: i32 = 88;
    /// `TAG_ITEM_TYPE_MSAW_INDICATOR`
    pub const MSAW_INDICATOR: i32 = 89;
    /// `TAG_ITEM_TYPE_SIMULATION_INDICATOR`
    pub const SIMULATION_INDICATOR: i32 = 90;
    /// `TAG_ITEM_TYPE_SIMULATION_WAYPOINT`
    pub const SIMULATION_WAYPOINT: i32 = 91;
    /// `TAG_ITEM_TYPE_ASSIGNED_HEADING_STATIC`
    pub const ASSIGNED_HEADING_STATIC: i32 = 92;
    /// `TAG_ITEM_TYPE_AIRLINE_NAME`
    pub const AIRLINE_NAME: i32 = 93;
    /// `TAG_ITEM_TYPE_SIMULATION_IAS`
    pub const SIMULATION_IAS: i32 = 94;
    /// `TAG_ITEM_TYPE_SIMULATION_ALTITUDE`
    pub const SIMULATION_ALTITUDE: i32 = 95;
    /// `TAG_ITEM_TYPE_SIMULATION_HEADING`
    pub const SIMULATION_HEADING: i32 = 96;
}

/// Built-in tag item function codes.
///
/// Mirrors the SDK's `TAG_ITEM_FUNCTION_*` constants.
pub mod tag_item_function {
    /// `TAG_ITEM_FUNCTION_NO`
    pub const NO: i32 = 0;
    /// `TAG_ITEM_FUNCTION_TOGGLE_ROUTE_DRAW`
    pub const TOGGLE_ROUTE_DRAW: i32 = 1;
    /// `TAG_ITEM_FUNCTION_TOGGLE_ITEM_DISPLAY`
    pub const TOGGLE_ITEM_DISPLAY: i32 = 2;
    /// `TAG_ITEM_FUNCTION_TOGGLE_FIR_COPX_DISPLAY`
    pub const TOGGLE_FIR_COPX_DISPLAY: i32 = 3;
    /// `TAG_ITEM_FUNCTION_TOGGLE_DEST_DISPLAY`
    pub const TOGGLE_DEST_DISPLAY: i32 = 4;
    /// `TAG_ITEM_FUNCTION_TOGGLE_PLANE_TYPE_DISPLAY`
    pub const TOGGLE_PLANE_TYPE_DISPLAY: i32 = 5;
    /// `TAG_ITEM_FUNCTION_TOGGLE_SI_STYLE`
    pub const TOGGLE_SI_STYLE: i32 = 6;
    /// `TAG_ITEM_FUNCTION_OPEN_FP_DIALOG`
    pub const OPEN_FP_DIALOG: i32 = 7;
    /// `TAG_ITEM_FUNCTION_HANDOFF_POPUP_MENU`
    pub const HANDOFF_POPUP_MENU: i32 = 8;
    /// `TAG_ITEM_FUNCTION_TAKE_HANDOFF`
    pub const TAKE_HANDOFF: i32 = 9;
    /// `TAG_ITEM_FUNCTION_NEXT_ROUTE_POINTS_POPUP`
    pub const NEXT_ROUTE_POINTS_POPUP: i32 = 10;
    /// `TAG_ITEM_FUNCTION_TEMP_ALTITUDE_POPUP`
    pub const TEMP_ALTITUDE_POPUP: i32 = 11;
    /// `TAG_ITEM_FUNCTION_ASSIGNED_SPEED_POPUP`
    pub const ASSIGNED_SPEED_POPUP: i32 = 12;
    /// `TAG_ITEM_FUNCTION_ASSIGNED_RATE_POPUP`
    pub const ASSIGNED_RATE_POPUP: i32 = 13;
    /// `TAG_ITEM_FUNCTION_ASSIGNED_HEADING_POPUP`
    pub const ASSIGNED_HEADING_POPUP: i32 = 14;
    /// `TAG_ITEM_FUNCTION_ASSIGNED_MACH_POPUP`
    pub const ASSIGNED_MACH_POPUP: i32 = 15;
    /// `TAG_ITEM_FUNCTION_TOGGLE_PREDICTION_DRAW`
    pub const TOGGLE_PREDICTION_DRAW: i32 = 16;
    /// `TAG_ITEM_FUNCTION_ASSIGNED_SID`
    pub const ASSIGNED_SID: i32 = 17;
    /// `TAG_ITEM_FUNCTION_ASSIGNED_STAR`
    pub const ASSIGNED_STAR: i32 = 18;
    /// `TAG_ITEM_FUNCTION_ASSIGNED_RUNWAY`
    pub const ASSIGNED_RUNWAY: i32 = 19;
    /// `TAG_ITEM_FUNCTION_ASSIGNED_NEXT_CONTROLLER`
    pub const ASSIGNED_NEXT_CONTROLLER: i32 = 20;
    /// `TAG_ITEM_FUNCTION_COPN_NAME`
    pub const COPN_NAME: i32 = 21;
    /// `TAG_ITEM_FUNCTION_COPX_NAME`
    pub const COPX_NAME: i32 = 22;
    /// `TAG_ITEM_FUNCTION_COPN_ALTITUDE`
    pub const COPN_ALTITUDE: i32 = 23;
    /// `TAG_ITEM_FUNCTION_COPX_ALTITUDE`
    pub const COPX_ALTITUDE: i32 = 24;
    /// `TAG_ITEM_FUNCTION_ACCEPT_MANUAL_COORDINATION`
    pub const ACCEPT_MANUAL_COORDINATION: i32 = 25;
    /// `TAG_ITEM_FUNCTION_COPN_COPX_ALTITUDE`
    pub const COPN_COPX_ALTITUDE: i32 = 26;
    /// `TAG_ITEM_FUNCTION_SET_CLEARED_FLAG`
    pub const SET_CLEARED_FLAG: i32 = 27;
    /// `TAG_ITEM_FUNCTION_SET_GROUND_STATUS`
    pub const SET_GROUND_STATUS: i32 = 28;
    /// `TAG_ITEM_FUNCTION_EDIT_SCRATCH_PAD`
    pub const EDIT_SCRATCH_PAD: i32 = 29;
    /// `TAG_ITEM_FUNCTION_RFL_POPUP`
    pub const RFL_POPUP: i32 = 30;
    /// `TAG_ITEM_FUNCTION_SQUAWK_POPUP`
    pub const SQUAWK_POPUP: i32 = 31;
    /// `TAG_ITEM_FUNCTION_COMMUNICATION_POPUP`
    pub const COMMUNICATION_POPUP: i32 = 32;
    /// `TAG_ITEM_FUNCTION_CORRELATE_POPUP`
    pub const CORRELATE_POPUP: i32 = 33;
    /// `TAG_ITEM_FUNCTION_SET_FP_STATUS`
    pub const SET_FP_STATUS: i32 = 34;
    /// `TAG_ITEM_FUNCTION_SET_ESTIMATE`
    pub const SET_ESTIMATE: i32 = 35;
    /// `TAG_ITEM_FUNCTION_SIMUL_TO_POPUP`
    pub const SIMUL_TO_POPUP: i32 = 37;
    /// `TAG_ITEM_FUNCTION_SIMUL_LAND_VACATE_POPUP`
    pub const SIMUL_LAND_VACATE_POPUP: i32 = 38;
    /// `TAG_ITEM_FUNCTION_SIMUL_TAXI_POPUP`
    pub const SIMUL_TAXI_POPUP: i32 = 39;
    /// `TAG_ITEM_FUNCTION_SIMUL_TAXI_BEHIND`
    pub const SIMUL_TAXI_BEHIND: i32 = 40;
    /// `TAG_ITEM_FUNCTION_SIMULATION_POPUP`
    pub const SIMULATION_POPUP: i32 = 41;
    /// `TAG_ITEM_FUNCTION_SIMUL_NEXT_WAYPOINTS`
    pub const SIMUL_NEXT_WAYPOINTS: i32 = 42;
    /// `TAG_ITEM_FUNCTION_SIMUL_HOLDING_POINTS`
    pub const SIMUL_HOLDING_POINTS: i32 = 43;
    /// `TAG_ITEM_FUNCTION_CONFLICT_DETECTION_TOOL2`
    pub const CONFLICT_DETECTION_TOOL2: i32 = 44;
    /// `TAG_ITEM_FUNCTION_SIMUL_ROUTES_POPUP`
    pub const SIMUL_ROUTES_POPUP: i32 = 45;
    /// `TAG_ITEM_FUNCTION_SET_GROUND_STATUS_ADVANCED`
    pub const SET_GROUND_STATUS_ADVANCED: i32 = 46;
}
