---
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:

permissions:
  contents: read

jobs:
  lint:
    strategy:
      fail-fast: false
      matrix:
        job:
          - lint
        include:
          - job: fmt
            toolchain: nightly
            components: rustfmt
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - if: ${{ matrix.toolchain }}
        uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1.17.0
        with:
          target: i686-pc-windows-msvc
          toolchain: ${{ matrix.toolchain }}
          components: ${{ matrix.components }}
      - if: ${{ ! matrix.toolchain }}
        uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1.17.0
        with:
          target: i686-pc-windows-msvc
      - uses: taiki-e/install-action@37f7c5781271959fb65b6b35224e28652ff2b63d # v2.87.0
        with:
          tool: just
      - uses: euroscope-rust/actions/install@f7d89d5d2fd9ac133f94b216345934565bc7926d # 0.0.3
      - run: just ci-${{ matrix.job }}
  build:
    strategy:
      fail-fast: false
      matrix:
        euroscope-version:
          - "latest"
          - "3.2.3.2"
          - "3.2.2.3"
    runs-on: windows-latest
    permissions:
      contents: read
      id-token: write
      attestations: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1.17.0
        with:
          target: i686-pc-windows-msvc
      - uses: taiki-e/install-action@37f7c5781271959fb65b6b35224e28652ff2b63d # v2.87.0
        with:
          tool: just
      - uses: euroscope-rust/actions/install@f7d89d5d2fd9ac133f94b216345934565bc7926d # 0.0.3
        with:
          version: "${{ matrix.euroscope-version }}"
      - run: just ci-build
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1.17.0
        with:
          target: i686-pc-windows-msvc
      - uses: taiki-e/install-action@37f7c5781271959fb65b6b35224e28652ff2b63d # v2.87.0
        with:
          tool: just
      - uses: euroscope-rust/actions/install@f7d89d5d2fd9ac133f94b216345934565bc7926d # 0.0.3
      - run: just ci-test
  ci-mark:
    if: always()
    needs:
      - lint
      - build
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: re-actors/alls-green@b5b5b37504aa4183270bd3d855c52a67f212be35
        with:
          jobs: ${{ toJSON(needs) }}